config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "pages#home"

  # dispay all routes
  # rails routes --expanded

  get "/about", controller: "pages", action: :about


  resources :articles, only: %i[index show new create edit update destroy]
  # resources :articles

  # resources :users, only: %i[index show new create update destroy]
  get "/signup", controller: "users", action: :new

  get "login", controller: "sessions", action: :new
  post "login", controller: "sessions", action: :create
  delete "logout", controller: "sessions", action: :destroy

  resources :users, except: [:new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }

  belongs_to :user, optional: true
  
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy

  validates :username,
              presence: true,
              uniqueness: { case_insensitive: true },
              length: { minimum: 3, maximum: 25 }

  VALID_EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  validates :email,
              format: { with: VALID_EMAIL_REGEX },
              presence: true,
              uniqueness: { case_insensitive: true },
              length: { maximum: 105 }

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  
  helper_method :current_user
  helper_method :logged_in?

  def current_user 
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def logged_in?
    # use 'current_user' as a boolean 
    !!current_user
  end

  def require_user
    if !logged_in? 
      flash[:alert] = "You must be logged in to perform this action"
      redirect_to login_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
before_action :set_article, only: [:show, :edit, :update, :destroy]
before_action :require_user, except: [:index, :show]
before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    per_page = 5
    @articles = Article.paginate(page: params[:page], per_page: per_page)

    # @articles = Article.all
  end

  def show
    # debugger
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    # debugger
    @article = Article.new(article_params)
    @article.user = current_user

    if @article.save
      flash[:notice] = "Article was created successfully."
      redirect_to @article
    else
      render :new
    end
  end

  def update 
    # debugger 
    @article.update(article_params)

    if @article.save
      flash[:notice] = "Article was updated successfuly."
      redirect_to @article
    else
      render :edit
    end
  end

  def destroy 
   @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end

  def require_same_user
    if @article.user != current_user && !current_user.admin?
      flash[:alert] = "You can only Edit or Delete your own article..."
      redirect_to @article
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @title = "Home"
    redirect_to articles_path if logged_in? 
  end

  def about
    @title = "Home"
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new       
  end

  def create 

    user = User.find_by(username: params[:session][:username].downcase)

    if user && user.authenticate(params[:session][:password])
        session[:user_id] = user.id
        flash[:notice] = "login successful"
        redirect_to user
    else
      flash.now[:alert] = "login failed"
      render 'new'
    end
  end

  def destroy 
    session[:user_id] = nil
    flash[:notice] = "logged out"
    redirect_to root_path
  end

  private

  def login_params
    params.require(:session).permit(:username, :password)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index 
    @users = User.all
    
    users_per_page = 3
    @users = User.paginate(page: params[:page], per_page: users_per_page)

  end

  def show 
    # @articles = Article.joins(:user)
    # @articles = @user.articles
    articles_per_page = 5
    @articles = @user.articles.paginate(page: params[:page], per_page: articles_per_page)
  end

  def new
    @user = User.new
  end

  def create 
    # debugger
    @user = User.new(user_params)
    if @user.save 
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to your Blog: #{@user.username}"
      redirect_to @user
    else 
      render 'new'
    end
  end

  def edit 
  end

  def update 
    @user.update(user_params)

    if @user.save 
      flash[:notice] = "Edit successfully saved"
      redirect_to @user
    else 
      redirect_to 'edit'
    end
  end

  def destroy  
    @user.destroy
    session[:user_id] = nil if current_user == @user
    flash[:notice] = "Account and all associated Articles successfully removed."
    redirect_to articles_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password, :admin)
  end

  def require_same_user
    if @user != current_user && !current_user.admin?
      flash[:alert] = "You can only Edit or Delete your own Profile..."
      redirect_to @user
    end
  end
end

app/helpers/application_helper.rb
require 'digest'
require 'uri'

module ApplicationHelper

  def gravatar_for(user, options={ size: 200 })
    # Assume you manually set the email_address here or get it from user input
    email_address = user.email.downcase
    
    # Create the SHA256 hash
    hash = Digest::SHA256.hexdigest(email_address)
    
    # Set default URL and size parameterss
    size = options[:size]
    default = "https://www.gravatar.com/avatar/?d=identicon&s=#{size}"

    # Compile the full URL with URI encoding for the parameters
    params = URI.encode_www_form('d' => default, 's' => size)
    image_src = "https://www.gravatar.com/avatar/#{hash}?#{params}"
    
    image_tag(image_src, alt: user.username, class: "rounded shadow mx-auto d-block")
  end


end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article.html.erb
<div class="container">
  <% @articles.each do |article| %>
    <div class="row justify-content-md-center ">
      <div class="col-8 mt-0 ">
        <div class="card text-center shadow mb-1 bg-white rounded">
          <div class="card-header fst-italic">
            by 
            <%= link_to article.user.username, 
                  user_path(article.user), 
                  class: "link-success text-decoration-none"  if article.user 
            %>
          </div>
          <div class="card-body"> 
            <h5 class="card-title"><%= link_to article.title, article_path(article), class: "link-success text-decoration-none" %></h5>
            <p class="card-text"><%= truncate(article.description, length:50) %></p>
            <%= link_to "show", article_path(article), class:"btn btn-outline-success" %>
            <% if logged_in? && (current_user == article.user || current_user.admin?) %>
              <%= link_to "edit", edit_article_path(article), class:"btn btn-outline-info" %>
              <%= link_to "delete", article_path(article), method: :delete, data: { turbo_confirm: "Are you sure?", turbo_method: "delete" }, class:"btn btn-outline-danger" %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(article.created_at) %>, ago. Edited <%= time_ago_in_words(article.updated_at)%> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/_form.html.erb
<div class="row justify-content-center">
  <div class="col-10">
    <%= render 'shared/errors', obj: @article %>
    <%= form_with(model: @article, class: "shadow p-3 mb-3 bg-primary rounded", data: {turbo: false}, local: true) do |f| %>
      <div class="form-group row">
        <%= f.label :title, class: "col-2 mb-3 col-form-label text-light" %>
        <div class="col-10">
          <%= f.text_field :title, class:"form-control mb-3 shadow rounded", placeholder: "Title of article..." %>
        </div>
      </div>

      <div class="form-group row mb-3">
        <%= f.label :description, class: "col-2 col-form-label text-light" %>
        <div class="col-10">
          <%= f.text_area :description, rows: 10, class:"form-control shadow rounded", placeholder: "Description of article..." %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.submit class: "btn btn-primary btn-outline-light btn-lg d-grid gap-2 col-2 mx-auto mt-4" %>
      </div>

    <% end %>

    <div class="mb-3">
      <%= link_to '[ Cancel and return to articles listing ]', articles_path, class: "text-info row justify-content-center" %>
    </div>

  </div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4 mb-4 text-white">Edit article: id: <%= @article.id %></h1>
<%= render 'form' %>  

app/views/articles/index.html.erb
<h1 class="text-center mt-4 mb-4 text-white">Listing All Articles</h1>

<% if logged_in? %>
  <div class="row justify-content-md-center ">
    <%= link_to "New Article", new_article_path, class:"btn btn-primary mb-3 text-center col-2" %>
  </div>
<% end %>

<div class="row justify-content-md-center mt-3 mb-1 ">
  <div class="apple_pagination col-3">
    <%= will_paginate @articles, :container => false %>
  </div>
</div>

<%=  render 'article' %>

<div class="row justify-content-md-center mt-3 mb-1 ">
  <div class="apple_pagination col-3">
    <%= will_paginate @articles, :container => false %>
  </div>
</div>

app/views/articles/new.html.erb
<h1 class="text-center mt-4 mb-4 text-white">Create new Article</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
  
<h2 class="text-center mt-4 mb-4 text-white"><%= @article.title  %></h2>

<% if logged_in? && current_user == @article.user %>

  <div class="row justify-content-md-center ">
    <%= link_to "New Article", new_article_path, class:"btn btn-primary mb-3 text-center col-2" %>
  </div>

<% end %>

<div class="container">

  <div class="row justify-content-md-center ">
    <div class="col-8 mt-4 ">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header fst-italic">
          <%= link_to @article.user.username, 
                user_path(@article.user.id), 
                class: "link-success text-decoration-none font-weight-bold"  if @article.user 
          %>
          <%= link_to gravatar_for(@article.user, size: 50), @article.user %>
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= link_to @article.title, article_path(@article), class: "link-success text-decoration-none" %></h5>
          <p class="card-text"><%= truncate(@article.description, length:50) %></p>
          <% if logged_in? && current_user == @article.user || current_user.admin? %>
            <%= link_to "edit", edit_article_path(@article), class:"btn btn-outline-info" %>
            <%= link_to "delete", article_path(@article), method: :delete, data: { turbo_confirm: "Are you sure?", turbo_method: "delete" }, class:"btn btn-outline-danger" %>
          <% end %>
        </div>
        <div class="card-footer text-muted">
          <small>Created <%= time_ago_in_words(@article.created_at) %>, ago. Edited <%= time_ago_in_words(@article.updated_at)%> ago</small>
        </div>
      </div>
    </div>

  </div>

</div>

app/views/layouts/_messages.html.erb
<div class="container mt-3">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Rails Alpha Blog" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'shared/navbar' %>
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<div>
<h1 class="display-2">About Page</h1>

<p><%= link_to "Articles Listing", articles_path %></p>
<p><%= link_to "Home Page", root_path %></p>
</div>

app/views/pages/home.html.erb
<div class="container" id="home-container">
  <div class="container-fluid text-sm-center text-white p-5 bg-secondary home-jumbotron">
      <h1 class="display-2">Alpha Blog</h1>
      <p class="lead">My Tech Blog...</p>
      <br>
      <button class="mt-3 btn btn-success btn-lg">
        <%= link_to "Sign Up...", signup_path,  class:"home-link text-white" %>
        <!-- <%= link_to "Sign Up (disabled)...", "#",  class:"home-link text-white" %> -->
      </button>
      <div>
        <br>
        <h4>Login credentials:</h3>
        <p>Username: arjuna</p>
        <p>Password: password </p>

      </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer id="sticky-footer" class="mt-4 flex-shrink-0 py-4 bg-dark text-white-50">
  <div class="container text-center">
    <small>Copyright &copy; 
      <%= link_to 'scrummingit.co.uk', "http://scrummingit.co.uk", class: "text-white-50" %>
    </small>
  </div>
</footer>

app/views/shared/_nav_links.html.erb
<div>
  <button class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
    <%= link_to 'Home', root_path, class: "text-danger" %>
  </button>

  <button class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
    <%= link_to 'About', about_path, class: "text-info" %>
  </button>

  <button class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
    <%= link_to 'Article listing', articles_path, class: "text-info" %>
  </button>


</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">

    <%= link_to "ALPHA BLOG", root_path, class: "navbar-brand", id: "logo" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <%= link_to "Bloggers", users_path, class: "nav-link" %>
        </li>
        
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Articles
          </a>
          <div class="dropdown-menu">
            <% if logged_in? %>
              <%= link_to "Create new article", new_article_path, class: "dropdown-item" %>
            <% end %>
            <%= link_to "View articles", articles_path, class: "dropdown-item" %>
          </div>
        </li>

        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= "(Admin)" if current_user.admin?  %>Profile [<%= current_user.username %>]
            </a>
            <div class="dropdown-menu">
              <%= link_to "View Your Profile", user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Edit your Profile", edit_user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Delete Account", user_path(current_user), class: "dropdown-item text-danger fw-bold", method: :delete, data: { turbo_confirm: "Are you sure?", turbo_method: "delete" } %>
            </div>
          </li>
        <% end %>

        <% if logged_in? %>
          <li class="nav-item">
            <%= link_to "Logout", logout_path, class: "nav-link", method: :delete, data: { turbo_method: "delete" } %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Signup", signup_path, class: "nav-link" %>
            <!-- <%= link_to "Signup(disabled)", "#", class: "nav-link" %> -->
          </li>
          <li class="nav-item">
            <%= link_to "Login", login_path, class: "nav-link" %>
          </li>
        <% end %>

      </ul>

      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/users/_form.html.erb
<div class="row justify-content-center">
  <div class="col-4">
    <%= render 'shared/errors', obj: @user %>
    <%= form_with(model: @user, class: "shadow p-3 mb-3 bg-primary rounded", data: {turbo: false}, local: true) do |f| %>
      <div class="form-group row">
        <%= f.label :username, class: "col-2 mb-3 col-form-label text-light" %>
        <div class="col-10">
          <%= f.text_field :username, class:"form-control mb-3 shadow rounded", placeholder: "enter your username..." %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :email, class: "col-2 mb-3 col-form-label text-light" %>
        <div class="col-10">
          <%= f.email_field :email, class:"form-control mb-3 shadow rounded", placeholder: "enter your email..." %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :password, class: "col-2 mb-3 col-form-label text-light" %>
        <div class="col-10">
          <%= f.password_field :password, class:"form-control mb-3 shadow rounded" %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.submit(@user.new_record? ? "signup" : "update account", class: "btn btn-primary btn-outline-light btn-lg d-grid gap-2 col-5 mx-auto mt-4") %>
      </div>

    <% end %>

    <div class="mb-3">
      <%= link_to '[ Cancel and return to articles listing ]', articles_path, class: "text-info row justify-content-center" %>
    </div>

  </div>
</div>

app/views/users/edit.html.erb
<h2 class="text-center mt-4 mb-4 text-white">Edit User</h2>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center mt-4 mb-4 text-white">Bloggers</h1>

<div class="row justify-content-md-center ">
  <%= link_to "New User", signup_path, class:"btn btn-primary mb-3 text-center col-2" %>
</div>

<div class="row justify-content-md-center mt-3 mb-1 ">
  <div class="apple_pagination col-3">
    <%= will_paginate @users, :container => false %>
  </div>
</div>

<div class="container">
  <% @users.each do |user| %>
    <div class="row justify-content-md-center ">
      <div class="col-6 mt-0 ">
        <div class="card text-center shadow mb-0 bg-white rounded">
          <div class="card-header fst-italic">
            <%= link_to user.username, user, class: "link-success text-decoration-none"  if user %>
          </div>

          <%= link_to gravatar_for(user, size: 150), user %>

          <div class="mt-1 fst-italic fw-bold">
            <%= pluralize(user.articles.count, "article") %>
          </div>

          <div class="card-body">
            <%= link_to "View Profile", user, class:"btn btn-outline-success" %>

            <% if logged_in? && current_user == user %>
              <%= link_to "Edit Profile", edit_user_path(user), class:"btn btn-outline-info" %>
            <% end %>

            <% if logged_in? && current_user.admin? %>
              <%= link_to "delete", user_path(user), 
                      method: :delete, 
                      data: { turbo_confirm: "Are you sure?", turbo_method: "delete" }, 
                      class:"btn btn-outline-danger" %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>
          </div>
        </div>
      </div>

    </div>
  <% end %>

</div>

<div class="row justify-content-md-center mt-1 mb-1 ">
  <div class="apple_pagination col-3">
    <%= will_paginate @users, :container => false %>
  </div>
</div>

app/views/users/new.html.erb
<h2 class="text-center mt-4 mb-4 text-white">SignUp</h2>
<%= render 'form' %>

app/views/users/show.html.erb
<div class="container">

  <h1 class="text-center mt-8 mb-4 text-white"><%= @user.username %>'s profile</h1>

  <%= gravatar_for @user, size: 300 %>

  <% if logged_in? && current_user == @user %>
    <div class="text-center mt-2">
      <%= link_to "Edit Profile", edit_user_path(@user), class:"btn btn-outline-info mb-3 text-center col-2" %>
    </div>
  <% end %>

  <div class="mt-4">
    <h3 class="text-center px-5 text-white">Articles</h3>


    <div class="row justify-content-md-center mt-3 mb-1 ">
      <div class="apple_pagination col-3">
        <%= will_paginate @articles, :container => false %>
      </div>
    </div>

    <%= render 'articles/article' %>

    <div class="row justify-content-md-center mt-3 mb-1 ">
      <div class="apple_pagination col-3">
        <%= will_paginate @articles, :container => false %>
      </div>
    </div>

  </div>

</div>